apiVersion: apps/v1
kind: Deployment
metadata:
  # The name of the deployment.
  name: {{ .Release.Name }}-dotnet-deploy
  labels:
    app: {{ .Release.Name }}-dotnet-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dotnet-deploy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dotnet-deploy
    spec:
      containers:
      - name: dotnet-server
        image: docker.io/jianzhiteh/test-mvc:latest
        ports:
        - containerPort: 80
        # volumeMounts:
        #   - mountPath: /app/appsettings2.json
        #     name: config-volume
        #     subPath: appsettings2.json
        env:
        - name: TEH_DEPLOYMENT
          value: "Hello_from_the_environment"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-configmap
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dotnet-deploy
spec:
  selector:
    app: {{ .Release.Name }}-dotnet-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
